<?php
/**
 * Configuration Vocabulary for Ipsum Generator
 */
class VOCAB {
    public $proper_nouns = [
        'World Class',
        'APIs',
        'Tabs vs Spaces',
        'GitHub',
        'BitBucket',
        'Whiteboard',
        'Jira',
        'Atlassian',
        'HighFive',
        'Manual Keyboard',
        'Atom',
        'IDE',
        'DIV Soup',
        'Demo Node',
        'UAT',
        'Slack',
        'Stack Overflow',
        'Middle Out',
        'Snack Dick',
        'SaaS'
    ];

    public $verbs = [
        'deploy',
        'commit',
        'revert',
        'cherry pick',
        'tune out',
        'apply',
        'maintenance',
        'design',
        'build',
        'develop',
        'refactor',
        'refuctor',
        'regress',
        'benchmark'
    ];

    public $direct_objects = [
        'developer',
        'agile',
        'standing desk',
        'coffee breaks',
        'ego',
        'methodology',
        'deploys',
        'waterfall',
        'ops',
        'sprint',
        'nutter butter',
        'stash',
        'server',
        'configuration',
        'assets',
        'UX',
        'UI',
        'blockers',
        'low-hanging fruit',
        'prod',
        'staging',
        'production',
        'bug',
        'cache',
        'exception handling',
        'snake-case',
        'humpCase',
        'doctype',
        'fear-driven development',
        'ego-driven development',
    ];

    public $conjunctions = [
        'and',
        'nor',
        'but',
        'or',
        'yet',
        'so',
        'for'
    ];

    public $prepositions = [
        'a',
        'an',
        'abeam',
        'aboard',
        'about',
        'above',
        'abreast',
        'abroad',
        'absent',
        'across',
        'adjacent',
        'after',
        'against',
        'along',
        'alongside',
        'amid',
        'among',
        'around',
        'as',
        'astride',
        'at',
        'atop',
        'bar',
        'before',
        'behind',
        'below',
        'beneath',
        'beside',
        'besides',
        'between',
        'beyond',
        'but',
        'by',
        'come',
        'despite',
        'down',
        'during',
        'except',
        'for',
        'from',
        'in',
        'inside',
        'into',
        'less',
        'like',
        'minus',
        'near',
        'notwithstanding',
        'of',
        'off',
        'on',
        'onto',
        'opposite',
        'out',
        'outside',
        'over',
        'pace',
        'past',
        'per',
        'post',
        'pre',
        'pro',
        'qua',
        're',
        'sans',
        'save',
        'short',
        'since',
        'than',
        'through',
        'throughout',
        'to',
        'toward',
        'towards',
        'under',
        'underneath',
        'unlike',
        'until',
        'up',
        'upon',
        'upside',
        'versus',
        'via',
        'vice',
        'vis-à-vis',
        'with',
        'within',
        'without',
        'worth',
        'according to',
        'adjacent to',
        'ahead of',
        'apart from',
        'as for',
        'as of',
        'as per',
        'as regards',
        'aside from',
        'astern of',
        'back to',
        'because of',
        'close to',
        'due to',
        'except for',
        'far from',
        'inside of',
        'instead of',
        'left of',
        'near to',
        'next to',
        'opposite of',
        'opposite to',
        'out from',
        'out of',
        'outside of',
        'owing to',
        'prior to',
        'pursuant to',
        'rather than',
        'regardless of',
        'right of',
        'subsequent to',
        'such as',
        'thanks to',
        'up to',
        'as far as',
        'as opposed to',
        'as soon as',
        'as well as',
        'at the behest of',
        'by means of',
        'by virtue of',
        'for the sake of',
        'in accordance with',
        'in addition to',
        'in case of',
        'in front of',
        'in lieu of',
        'in order to',
        'in place of',
        'in point of',
        'in spite of',
        'on account of',
        'on behalf of',
        'on top of',
        'with regard',
        'with respect to',
        'with a view to'
    ];
}
